package ch.admin.bj.swiyu.core.business.common.exceptions;

public enum BusinessExceptionErrorCode {
    DATA_INVALID,
    DATA_INVALID_VIRUS_DETECTED,
    RESOURCE_NOT_FOUND,
    RESOURCE_FORBIDDEN,
    ACTION_FORBIDDEN,
    PARTNER_IS_NOT_GOVERNMENTAL,
    BUSINESS_DATA_INTEGRITY_VIOLATION,
    CRYPTO_INTEGRITY_VALIDATION_FAILED,
    DID_RESOLVE_FAILED,
    DOCUMENT_NOT_FOUND,
    IDENTIFIER_VALIDATION_FAILED,
    INVALID_PAGINATION,
    MAX_SIZE_EXCEEDED,
    OBJECT_COUNT_LIMIT_REACHED,
    STATUS_LIST_VALIDATION_FAILED,
    TRUST_ONBOARDING_DOCUMENT_VALIDATION_FAILED,
    VC_SCHEMA_SUBMISSION_NOT_FOUND,
    VC_TYPE_METADATA_VALIDATION_FAILED,
    VQPS_PUBLICATION_FAILED,
    VQPS_PUBLICATION_WAIT_TIMEOUT,
}
