package ch.admin.bj.swiyu.core.business.common.utils;

import static org.junit.jupiter.api.Assertions.*;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.Test;

class UUIDUtilTest {

    @Test
    void optionalUUID_shouldReturnPresentOptional_forValidUUID() {
        // Arrange
        var validUuidString = "123e4567-e89b-12d3-a456-426614174000";
        var expectedUuid = UUID.fromString(validUuidString);

        // Act
        Optional<UUID> result = UUIDUtil.optionalUUID(validUuidString);

        // Assert
        assertTrue(result.isPresent(), "Optional should be present for a valid UUID");
        assertEquals(expectedUuid, result.get(), "The UUID in the optional should match the expected UUID");
    }

    @Test
    void optionalUUID_shouldReturnEmptyOptional_forInvalidUUIDString() {
        // Arrange
        var invalidString = "not-a-real-uuid";

        // Act
        Optional<UUID> result = UUIDUtil.optionalUUID(invalidString);

        // Assert
        assertTrue(result.isEmpty(), "Optional should be empty for an invalid UUID string");
    }

    @Test
    void optionalUUID_shouldReturnEmptyOptional_forEmptyString() {
        // Arrange
        var emptyString = "";

        // Act
        Optional<UUID> result = UUIDUtil.optionalUUID(emptyString);

        // Assert
        assertTrue(result.isEmpty(), "Optional should be empty for an empty string");
    }

    @Test
    void optionalUUID_shouldThrowNullPointerException_forNullInput() {
        String nullString = null;
        assertThrows(
            NullPointerException.class,
            () -> UUIDUtil.optionalUUID(nullString),
            "Passing null should throw NullPointerException"
        );
    }

    /**
     * This test is for code coverage, specifically for the private constructor
     * generated by Lombok's @UtilityClass annotation.
     */
    @Test
    void testPrivateConstructor() {
        assertThrows(
            InvocationTargetException.class,
            () -> {
                Constructor<UUIDUtil> constructor = UUIDUtil.class.getDeclaredConstructor();
                constructor.setAccessible(true);
                constructor.newInstance();
            },
            "Utility class constructor should not be invokable"
        );

        // Bonus: Check for the specific exception Lombok throws inside the InvocationTargetException
        try {
            Constructor<UUIDUtil> constructor = UUIDUtil.class.getDeclaredConstructor();
            constructor.setAccessible(true);
            constructor.newInstance();
        } catch (InvocationTargetException e) {
            // Lombok's @UtilityClass constructor throws UnsupportedOperationException
            assertInstanceOf(
                UnsupportedOperationException.class,
                e.getCause(),
                "The cause should be UnsupportedOperationException for a @UtilityClass"
            );
        } catch (Exception e) {
            fail("Unexpected exception type thrown: " + e.getClass().getName());
        }
    }
}
