CREATE TABLE trust_onboarding_submission
(
    id                  UUID     NOT NULL,
    partner_id          UUID     NOT NULL,
    version             BIGINT   NOT NULL,
    entity_email        VARCHAR(255),
    status              SMALLINT NOT NULL,
    uid                 VARCHAR(255),
    last_modified_at    TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by    VARCHAR(255),
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    created_by          VARCHAR(255),
    entity_name_de      VARCHAR(255),
    entity_name_fr      VARCHAR(255),
    entity_name_it      VARCHAR(255),
    entity_name_en      VARCHAR(255),
    entity_name_rm      VARCHAR(255),
    entity_street       VARCHAR(255),
    entity_postal_code  VARCHAR(255),
    entity_city         VARCHAR(255),
    entity_country      VARCHAR(255),
    contact_first_name  VARCHAR(255),
    contact_last_name   VARCHAR(255),
    contact_email       VARCHAR(255),
    contact_phone       VARCHAR(255),
    contact_street      VARCHAR(255),
    contact_postal_code VARCHAR(255),
    contact_city        VARCHAR(255),
    contact_country     VARCHAR(255),
    CONSTRAINT pk_trustonboardingsubmission PRIMARY KEY (id)
);