app:
  identifier-registry:
    did-tdw-route-template: "https://localhost:8190/api/v1/did/{0}"
    did-web-template: "did:web:localhost%3A8190:api:v1:did:{0}"
    default-public-resolve-url-template: https://localhost:8190/api/v1/did/%s
    additional-public-resolve-url-templates:
      - https://identifier-reg-d.trust-infra.swiyu.admin.ch/api/v1/did/%s
      - https://identifier-data-service-d.apps.p-szb-ros-shrd-npr-01.cloud.admin.ch/api/v1/did/%s
      - http://localhost:8190/api/v1/did/%s
  status-registry:
    data-url-template: https://localhost:8290/api/v1/statuslist/{0}.{1}
  trust-registry:
    data-service-base-url: http://localhost:8390/

spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.shared.yml

logging:
  level:
    io.confluent.kafka: WARN
    org.springframework.kafka: WARN
    ch.admin.bit.jeap.messaging.kafka: WARN
    org.apache.kafka: WARN